### ISSUE TITLE
[bug]: Configurator crashing on first start, restart needed for public/tls.cert to be valid

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/lnd-wrapper#35]
Jan 12 16:10:40 embassy-30297ba3 a027314c277e[4645]: Error: missing field `identity_pubkey` at line 1 column 211

Possibly related to #29 and #31

**Comment by ProofOfKeags** [comment]
Test case is:
- Install LND
- Install THub
- Start both
- Uninstall LND
- Reinstall LND
- LND will crash when started here and must be restarted to work properly

**Comment by chrisguida** [comment]
@kn0wmad can you report whether TH is working on the first try after a migrate? that should close out this bug

**Comment by chrisguida** [comment]
Just tested a migration, this bug is still present

**Comment by kn0wmad** [comment]
It does seem to be working on first try for me.  IBD has not completed if that makes a difference

**Comment by chrisguida** [comment]
@kn0wmad have you successfully logged into Thunderhub?

**Comment by kn0wmad** [comment]
No, it is 'unable to connect to node,' but is this due to IBD still in progress?

**Comment by chrisguida** [comment]
no, that is how this bug presents.

**Comment by chrisguida** [comment]
Problem is that LND is failing to keep the private and public copies of the tls cert in sync, so TH is using an old cert to connect to LND.

**Comment by ProofOfKeags** [comment]
> Just tested a migration, this bug is still present

There isn't a way to fix it during migration. Sorry.

**Comment by chrisguida** [comment]
That is not the problem. The problem is that LND is crashing
