### ISSUE TITLE
Watchtowers are Unusable

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/lnd-wrapper#47]
Currently we don't have enough configuration flexibility to make watchtowers actually work. The watchtower client and watchtower addresses can be enabled but we don't expose a means of configuring external watchtowers and therefore it is a useless feature. We need to make sure that we can actually configure watchtowers. Unfortunately the config options have been deprecated and this has to be done through an interactive process with the `wtclient` api.

**Comment by islandbitcoin** [comment]
fixed in
https://github.com/Start9Labs/lnd-wrapper/pull/72
