### ISSUE TITLE
Add description to "Tor Config"

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/lnd-wrapper#49]
Better to have a description IMO, but another reason is actually optics. Without a description for "Tor Config", the items below it look like they are nested under it.

<img width="796" alt="Screen Shot 2022-05-13 at 9 50 46 AM" src="https://user-images.githubusercontent.com/9935159/168322625-f59f5750-d415-41fb-a8ec-b8c87eb13619.png">

**Comment by ProofOfKeags** [comment]
Perhaps we should also cut a FE ticket against embassy-os to align these values more effectively. Alternatively change the colors of the available descriptions to green, and then put items without descriptions in grey.

**Comment by MattDHill** [comment]
Agree, FE ticket incoming.
