### ISSUE TITLE
[bug] Common crashes w/ `Exit code: 1 Details: write /dev/stdout: broken pipe`

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/lnd-wrapper#54]
The service lnd has crashed with the following exit code: 1 Details: write /dev/stdout: broken pipe

Occurs several times per day
EOS v0.3.1
LND v0.14.2.1

Lightning Terminal seems to crash an hour after this occurs.  No further symptoms noticed at this time

**Comment by chrisguida** [comment]
@kn0wmad @dr-bonez is this still an issue? can we close?

**Comment by islandbitcoin** [comment]
@kn0wmad @dr-bonez  can we close this?

**Comment by kn0wmad** [comment]
I've not run into it or heard of a support call.  I'm closing for now, can re-open if need be
