### ISSUE TITLE
Import from Umbrel action can easily take into account different Umbrel versions

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/lnd-wrapper#63]
We can either make a second action for Umbrel 0.5 migrations but given that the stop script that needs to be run is in the same location on both versions of Umbrel and the only relevant difference (afaict) is the location of the LND directory the action can probably be made more sophisticated and be able to migrate LND from either Umbrel version.

**Comment by ProofOfKeags** [comment]
The input spec can take most if not all of the same elements that the config spec can do so a simple enum would suffice. If you need different info in each case (I doubt this is true) you can use a union.
